openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://127.0.0.1:8080
  description: Generated server url
paths:
  /api/basket/offer:
    put:
      tags:
      - webshop-controller
      operationId: offer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BasketItem"
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/BasketDto"
  /api/basket/buy/{menhirId}:
    post:
      tags:
      - webshop-controller
      operationId: exchangeFor
      parameters:
      - name: menhirId
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
  /api:
    get:
      tags:
      - webshop-controller
      operationId: welcome
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/menhirs:
    get:
      tags:
      - webshop-controller
      operationId: getAllMenhirs
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MenhirDto"
  /:
    get:
      tags:
      - webshop-controller
      operationId: getBasket_1
      responses:
        "200":
          description: OK
  /api/basket:
    delete:
      tags:
      - webshop-controller
      operationId: leave
      responses:
        "200":
          description: OK
components:
  schemas:
    BasketItem:
      type: object
      properties:
        name:
          type: string
        count:
          type: integer
          format: int32
    BasketDto:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/BasketItem"
    MenhirDto:
      type: object
      properties:
        id:
          type: string
          format: uuid
        weight:
          type: number
          format: double
        stoneType:
          type: string
        decorativeness:
          type: string
          enum:
          - PLAIN
          - SIMPLE
          - DECORATED
          - ORNATE
          - MASTERWORK
        description:
          type: string
